package com.acl.formaliteenvironnementapi.models.enumeration;

public enum NatureAutorisation {
	
	AUTORISATION_POISSON,
	AUTORISATION_PRODUITS_LAITIERS,
	AUTORISATION_VOLAILLES,
	AUTORISATION_VIANDES_VOLAILLES,
	AUTORISATION_TRANSIT(),
	AUTORISATION_TRANSIT_DEPOTAGE;
	

}
