
CREATE TABLE MSW_PAYS
(
    PAYS_CODE                  VARCHAR2(5 BYTE) NOT NULL,
    PAYS_NOM                   VARCHAR2(255 BYTE),
    CONSTRAINT PK_MSW_PAYS     PRIMARY KEY (PAYS_CODE),
    CONSTRAINT UK_MSW_PAYS_1   UNIQUE(PAYS_NOM)
);

CREATE TABLE MSW_PORTS
(
    PORT_CODE                   VARCHAR2(5 BYTE) NOT NULL,
    PAYS_CODE                   VARCHAR2(5 BYTE) NOT NULL,
    PORT_LOCODE                 VARCHAR2(5 BYTE) NOT NULL,
    PORT_NOM                    VARCHAR2(255 BYTE),
    CONSTRAINT PK_MSW_PORTS     PRIMARY KEY (PORT_CODE),
    CONSTRAINT UK_MSW_PORTS_1   UNIQUE(PORT_NOM)
);


CREATE SEQUENCE SEQ_MSW_APPLIS MINVALUE 1 INCREMENT BY 1 START WITH 1;

CREATE TABLE MSW_APPLIS
(
    APPLI_ID                   NUMBER(19) NOT NULL,
    APPLI_NAME                 VARCHAR2(255 BYTE),
    APPLI_STATUS               NUMBER(1) DEFAULT 1,   
    APPLI_ADD_DATE             TIMESTAMP,
    APPLI_UPDATE_DATE          TIMESTAMP,
    APPLI_DESC                 VARCHAR2(500 BYTE),
    CONSTRAINT PK_MSW_APPLIS   PRIMARY KEY (APPLI_ID),
    CONSTRAINT UK_MSW_APPLIS_1 UNIQUE(APPLI_NAME)
);


CREATE SEQUENCE SEQ_MSW_PORTS_APPLIS MINVALUE 1 INCREMENT BY 1 START WITH 1;

CREATE TABLE MSW_PORTS_APPLIS
(
    PORTAPPLI_ID                     NUMBER(19) NOT NULL,
    APPLI_ID                         NUMBER(19) NOT NULL,
    PORT_CODE                        VARCHAR2(5 BYTE) NOT NULL,
    PORTAPPLI_URL                    VARCHAR2(255 BYTE)NOT NULL,
    PORTAPPLI_ADD_DATE               TIMESTAMP,
    PORTAPPLI_UPDATE_DATE            TIMESTAMP,
    CONSTRAINT PK_MSW_PORTS_APPLIS   PRIMARY KEY (PORTAPPLI_ID),
    CONSTRAINT UK_MSW_PORTS_APPLIS_1 UNIQUE(APPLI_ID, PORT_CODE),
    CONSTRAINT UK_MSW_PORTS_APPLIS_2 UNIQUE(PORTAPPLI_URL)
);

CREATE SEQUENCE SEQ_MSW_CLIENTS MINVALUE 1 INCREMENT BY 1 START WITH 1;

CREATE TABLE MSW_CLIENTS
(
    CLIENT_ID                        NUMBER(19) NOT NULL,
    CLIENT_NOM                       VARCHAR2(255 BYTE) NOT NULL,
    CLIENT_COMPTE                    VARCHAR2(30 BYTE) NOT NULL,
    PAYS_CODE                        VARCHAR2(5 BYTE) NOT NULL,    
    CONSTRAINT PK_MSW_CLIENTS  PRIMARY KEY (CLIENT_ID),
    CONSTRAINT UK_MSW_CLIENTS_1 UNIQUE(CLIENT_ID, PAYS_CODE),
    CONSTRAINT UK_MSW_CLIENTS_2 UNIQUE(CLIENT_COMPTE)
);

CREATE SEQUENCE SEQ_MSW_PORTS_CLIENTS MINVALUE 1 INCREMENT BY 1 START WITH 1;

CREATE TABLE MSW_PORTS_CLIENTS
(
    PORTCLIENT_ID                     NUMBER(19) NOT NULL,    
    PORT_CODE                         VARCHAR2(5 BYTE) NOT NULL, 
    CLIENT_ID                         NUMBER(19) NOT NULL,
    PORT_CODE_CLIENT                  VARCHAR2(155 BYTE) NOT NULL, 
    CONSTRAINT PK_MSW_PORTS_CLIENTS   PRIMARY KEY (PORTCLIENT_ID),
    CONSTRAINT UK_MSW_PORTS_CLIENTS_1 UNIQUE(CLIENT_ID, PORT_CODE)
);

CREATE SEQUENCE SEQ_MSW_GROUPES MINVALUE 1 INCREMENT BY 1 START WITH 1;

CREATE TABLE MSW_GROUPES
(
    GROUPE_ID                        NUMBER(10) NOT NULL,
    GROUPE_NOM                      VARCHAR2(255 BYTE) NOT NULL,       
    CONSTRAINT PK_MSW_GROUPES       PRIMARY KEY (GROUPE_ID),
    CONSTRAINT UK_MSW_GROUPES_1     UNIQUE(GROUPE_NOM)
);


CREATE SEQUENCE SEQ_MSW_GROUPES_CLIENTS MINVALUE 1 INCREMENT BY 1 START WITH 1;

CREATE TABLE MSW_GROUPES_CLIENTS
(
    GROUPECLIENT_ID                          NUMBER(19) NOT NULL,
    GROUPE_ID                                NUMBER(10) NOT NULL, 
    CLIENT_ID                                NUMBER(19) ,
    CONSTRAINT PK_MSW_GROUPES_CLIENTS       PRIMARY KEY (GROUPECLIENT_ID),
    CONSTRAINT UK_MSW_GROUPES_CLIENTS_1     UNIQUE(GROUPE_ID, CLIENT_ID)    
);

CREATE SEQUENCE SEQ_MSW_USERS MINVALUE 1 INCREMENT BY 1 START WITH 1;

CREATE TABLE MSW_USERS
(
    USER_ID                   NUMBER(19) NOT NULL,
    CLIENT_ID                 NUMBER(19),
    USER_FULLNAME             VARCHAR2(255 BYTE),
    USER_LOGIN                VARCHAR2(255 BYTE),
    USER_PASSWORD             VARCHAR2(255 BYTE),
    USER_MAIL                 VARCHAR2(255 BYTE),
    USER_STATUS               NUMBER(1) DEFAULT 1,
    USER_ADD_DATE             TIMESTAMP,
    USER_UPDATE_DATE          TIMESTAMP,   
    CONSTRAINT PK_MSW_USERS   PRIMARY KEY (USER_ID),
    CONSTRAINT UK_MSW_USERS_1 UNIQUE(USER_MAIL),
    CONSTRAINT UK_MSW_USERS_2 UNIQUE(USER_LOGIN)
);

CREATE SEQUENCE SEQ_MSW_ROLES MINVALUE 1 INCREMENT BY 1 START WITH 1;

CREATE TABLE MSW_ROLES 
(
  ROLE_ID                    NUMBER(10) NOT NULL,
  ROLE_NAME                  VARCHAR2(255 BYTE) NOT NULL,
  ROLE_DESC                  VARCHAR2(255 BYTE),
  CONSTRAINT PK_MSW_ROLES    PRIMARY KEY (ROLE_ID),
  CONSTRAINT UK_MSW_ROLES_1  UNIQUE(ROLE_NAME)
);

CREATE SEQUENCE SEQ_MSW_USERS_APPLIS MINVALUE 1 INCREMENT BY 1 START WITH 1;

CREATE TABLE MSW_USERS_APPLIS
(
    USERAPPLI_ID                      NUMBER(19) NOT NULL,
    PORT_CODE                         VARCHAR2(5 BYTE) NOT NULL,
    APPLI_ID                          NUMBER(10) NOT NULL, 
    GROUPE_ID                         NUMBER(10) NOT NULL,
    USERAPPLI_ADD_DATE                TIMESTAMP,
    USERAPPLI_UPDATE_DATE             TIMESTAMP,   
    CONSTRAINT PK_MSW_USERS_APPLIS    PRIMARY KEY (USERAPPLI_ID),
    CONSTRAINT UK_MSW_USERS_APPLIS_1  UNIQUE(GROUPE_ID, APPLI_ID,PORT_CODE)
);


CREATE SEQUENCE SEQ_MSW_USERS_ROLES MINVALUE 1 INCREMENT BY 1 START WITH 1;

CREATE TABLE MSW_USERS_ROLES 
(
  USER_ID                            NUMBER(19) NOT NULL,  
  ROLE_ID                            NUMBER(10) NOT NULL,  
  CONSTRAINT PK_MSW_USERS_ROLES      PRIMARY KEY (USER_ID, ROLE_ID)
 );

CREATE TABLE MSW_CONNECTED_USER(
                                   ID NUMBER NOT NULL ENABLE,
                                   USER_LOGIN VARCHAR2(250 BYTE) NOT NULL,
                                   COMPTECLIENT VARCHAR2(250 BYTE) NOT NULL,
                                   SESSION_ID VARCHAR2(500 BYTE),
                                   COUNTRY_CODE VARCHAR2(50 BYTE),
                                   PORT_CODE   VARCHAR(50 BYTE),
                                        DATE_CONNEXION TIMESTAMP,
)


CREATE TABLE MSW_LOGGED_USER(
                                   ID NUMBER NOT NULL ENABLE,
                                   USER_LOGIN VARCHAR2(50 BYTE) NOT NULL,
                                   COMPTECLIENT VARCHAR2(50 BYTE) NOT NULL,
                                   SESSION_ID VARCHAR2(100 BYTE),
                                   FULLNAME VARCHAR2(100 BYTE),
                                   COUNTRY_CODE VARCHAR2(50 BYTE),
                                   PORT_CODE   VARCHAR(50 BYTE),
                                   DATE_CONNEXION TIMESTAMP,
                                   DATE_DECONNEXION TIMESTAMP,
                                    CREATED_AT    TIMESTAMP,
                                    UPDATE_AT     TIMESTAMP


    CONSTRAINT PK_MSW_LOGGED_USER PRIMARY KEY (ID),
)

ALTER TABLE MSW_CONNECTED_USER ADD CONSTRAINT PK_MSW_CONNECTED_USER PRIMARY KEY (ID);


CREATE SEQUENCE  SEQ_MSW_CONNECTED_USER  MINVALUE 1 INCREMENT BY 1 START WITH 1;


COMMIT;


ALTER TABLE MSW_PORTS ADD CONSTRAINT FK_MSW_PORTS_1 FOREIGN KEY (PAYS_CODE) REFERENCES MSW_PAYS (PAYS_CODE) ON DELETE CASCADE;

ALTER TABLE MSW_PORTS_APPLIS ADD CONSTRAINT FK_MSW_PORTS_APPLIS_1 FOREIGN KEY (PORT_CODE) REFERENCES MSW_PORTS (PORT_CODE) ON DELETE CASCADE;
ALTER TABLE MSW_PORTS_APPLIS ADD CONSTRAINT FK_MSW_PORTS_APPLIS_2 FOREIGN KEY (APPLI_ID) REFERENCES MSW_APPLIS (APPLI_ID) ON DELETE CASCADE;

ALTER TABLE MSW_CLIENTS ADD CONSTRAINT FK_MSW_CLIENTS_1 FOREIGN KEY (PAYS_CODE) REFERENCES MSW_PAYS (PAYS_CODE) ON DELETE CASCADE;

ALTER TABLE MSW_PORTS_CLIENTS ADD CONSTRAINT FK_MSW_PORTS_CLIENTS_1 FOREIGN KEY (CLIENT_ID) REFERENCES MSW_CLIENTS (CLIENT_ID) ON DELETE CASCADE;
ALTER TABLE MSW_PORTS_CLIENTS ADD CONSTRAINT FK_MSW_PORTS_CLIENTS_2 FOREIGN KEY (PORT_CODE) REFERENCES MSW_PORTS (PORT_CODE) ON DELETE CASCADE;


ALTER TABLE MSW_GROUPES_CLIENTS ADD CONSTRAINT FK_MSW_GROUPES_CLIENTS_1 FOREIGN KEY (CLIENT_ID) REFERENCES MSW_CLIENTS (CLIENT_ID) ON DELETE CASCADE;
ALTER TABLE MSW_GROUPES_CLIENTS ADD CONSTRAINT FK_MSW_GROUPES_CLIENTS_2 FOREIGN KEY (GROUPE_ID) REFERENCES MSW_GROUPES (GROUPE_ID) ON DELETE CASCADE;


ALTER TABLE MSW_USERS ADD CONSTRAINT FK_MSW_USERS_1 FOREIGN KEY (CLIENT_ID) REFERENCES  MSW_CLIENTS (CLIENT_ID) ON DELETE CASCADE;


ALTER TABLE MSW_USERS_APPLIS ADD CONSTRAINT FK_MSW_USERS_APPLIS_1 FOREIGN KEY (APPLI_ID)  REFERENCES MSW_APPLIS (APPLI_ID) ON DELETE CASCADE;
ALTER TABLE MSW_USERS_APPLIS ADD CONSTRAINT FK_MSW_USERS_APPLIS_2 FOREIGN KEY (USER_ID)   REFERENCES  MSW_USERS (USER_ID)   ON DELETE CASCADE;  
ALTER TABLE MSW_USERS_APPLIS ADD CONSTRAINT FK_MSW_USERS_APPLIS_3 FOREIGN KEY (PORT_CODE) REFERENCES  MSW_PORTS (PORT_CODE) ON DELETE CASCADE;

ALTER TABLE MSW_USERS_ROLES ADD CONSTRAINT FK_MSW_USERS_ROLES_1 FOREIGN KEY (ROLE_ID) REFERENCES MSW_ROLES (ROLE_ID) ON DELETE CASCADE;
ALTER TABLE MSW_USERS_ROLES ADD CONSTRAINT FK_MSW_USERS_ROLES_2 FOREIGN KEY (USER_ID) REFERENCES  MSW_USERS (USER_ID) ON DELETE CASCADE; 

COMMIT;

ALTER TABLE MSW_GROUPES ADD (GROUPE_DUREE_PASSWORD NUMBER(8) DEFAULT 45 NOT NULL ) ;

ALTER TABLE MSW_USERS ADD (USER_DATE_INSCRIPTION TIMESTAMP ) ;
ALTER TABLE MSW_USERS ADD (USER_DATE_EXP_PASSWORD DATE ) ;
ALTER TABLE MSW_USERS ADD (USER_DATE_ACTIVATION TIMESTAMP ) ;
ALTER TABLE MSW_USERS ADD (USER_DATE_CHANG_PWD  TIMESTAMP ) ;
ALTER TABLE MSW_USERS ADD (USER_FONCTION VARCHAR2(255 BYTE) ) ;
ALTER TABLE MSW_USERS ADD (USER_MOBILE VARCHAR2(255 BYTE) ) ;

ALTER TABLE MSW_USERS ADD (STRUCTURE_ID  NUMBER(19)) ;

COMMIT;

CREATE TABLE MSW_STRUCTURES
(
    STRUCTURE_ID                      NUMBER(19) NOT NULL,
    STRUCTURE_PARENTE_ID              NUMBER(19),
    PAYS_CODE                         VARCHAR2(5 BYTE) NOT NULL,  
    STRUCTURE_NOM                     VARCHAR2(255 BYTE) NOT NULL,
    STRUCTURE_ADRESSE                 VARCHAR2(255 BYTE),
    STRUCTURE_SITE_WEB                VARCHAR2(255 BYTE),
    STRUCTURE_EMAIL                   VARCHAR2(255 BYTE),
    STRUCTURE_TELEPHONE               VARCHAR2(255 BYTE),
    CONSTRAINT PK_MSW_STRUCTURES      PRIMARY KEY (STRUCTURE_ID),
    CONSTRAINT UK_MSW_STRUCTURES_1    UNIQUE(STRUCTURE_ID, PAYS_CODE)
   
);

CREATE SEQUENCE SEQ_MSW_STRUCTURES MINVALUE 1 INCREMENT BY 1 START WITH 1;

ALTER TABLE MSW_GROUPES_CLIENTS ADD (STRUCTURE_ID NUMBER(19));

ALTER TABLE MSW_PORTS_CLIENTS ADD (STRUCTURE_ID NUMBER(19));

ALTER TABLE MSW_APPLIS ADD (APPLI_LOGO VACHAR2(255))

COMMIT;

ALTER TABLE MSW_STRUCTURES ADD CONSTRAINT FK_MSW_STRUCTURES_1 FOREIGN KEY (STRUCTURE_PARENTE_ID) REFERENCES  MSW_STRUCTURES (STRUCTURE_ID) ON DELETE CASCADE;

ALTER TABLE MSW_STRUCTURES ADD CONSTRAINT FK_MSW_STRUCTURES_2 FOREIGN KEY (PAYS_CODE) REFERENCES MSW_PAYS (PAYS_CODE) ON DELETE CASCADE;

ALTER TABLE MSW_USERS ADD CONSTRAINT FK_MSW_USERS_2 FOREIGN KEY (STRUCTURE_ID) REFERENCES  MSW_STRUCTURES (STRUCTURE_ID) ON DELETE CASCADE;

ALTER TABLE MSW_GROUPES_CLIENTS ADD CONSTRAINT FK_MSW_GROUPES_CLIENTS_3 FOREIGN KEY (STRUCTURE_ID) REFERENCES  MSW_STRUCTURES (STRUCTURE_ID) ON DELETE CASCADE;

ALTER TABLE MSW_PORTS_CLIENTS ADD CONSTRAINT FK_MSW_PORTS_CLIENTS_3 FOREIGN KEY (STRUCTURE_ID) REFERENCES  MSW_STRUCTURES (STRUCTURE_ID) ON DELETE CASCADE;

COMMIT;


// FORMALITE APPLICATION

CREATE SEQUENCE SEQ_MSW_FORMALITE_APPLI MINVALUE 1 INCREMENT BY 1 START WITH 1;


CREATE TABLE MSW_FORMALITE_APPLI
(
    ID                          NUMBER(19) NOT NULL,
    APPLI_ID                    NUMBER(19) NOT NULL,
    FORMALITE_NOM               VARCHAR2(255 BYTE) NOT NULL,
    FORMALITE_DESCRIPTION       VARCHAR2(255 BYTE),
    FORMALITE_URL                VARCHAR2(255 BYTE),
    FORMALITE_ADD_DATE                TIMESTAMP,
    FORMALITE_UPDATE_DATE             TIMESTAMP,
    CONSTRAINT PK_MSW_FORMALITE_APPLI      PRIMARY KEY (APPLI_ID)
);

ALTER TABLE MSW_FORMALITE_APPLI ADD CONSTRAINT FK_APPLI_FORMALITE FOREIGN KEY (APPLI_ID) references MSW_APPLIS(APPLI_ID)