alter table FORMALITE
    add createdAt TIMESTAMP;

alter table FORMALITE
    add updateAt TIMESTAMP;


ALTER TABLE DET_AUTORISATION_PRODUIT ADD CONSTRAINT FK_DET_AUTORISATION FOREIGN KEY (ID_AUTORISATION) REFERENCES
    AUTORISATION (ID) ON DELETE CASCADE;

ALTER TABLE DET_AUTORISATION_PRODUIT ADD CONSTRAINT FK_DET_PRODUIT FOREIGN KEY (ID_PRODUIT) REFERENCES
    PRODUIT (ID) ON DELETE CASCADE;


CREATE TABLE TYPE_AGREMENT
(
    ID                     NUMBER(8) NOT NULL,
    ETAT_AGREMENT          VARCHAR2(50 BYTE),
    LIBELLE                VARCHAR2(100 BYTE),

    CONSTRAINT PK_TYPE_AGREMENT  PRIMARY KEY (ID),
);

CREATE TABLE FEEDBACK_SRV_PAIEMENT
(
    ID                     NUMBER(8) NOT NULL,
    ID_FORMALITE          NUMBER(8),
    RECORD                VARCHAR2(100 BYTE),
    PROCESS                VARCHAR2(100 BYTE),
    STEP                VARCHAR2(100 BYTE),
    FB_ORDER                NUMBER(8),
    TRANSACTION_ID          VARCHAR2(100 BYTE),
    FEEDBACKTASKID          VARCHAR2(100 BYTE),
    DESCRIPTION             VARCHAR2(150 BYTE),
    CREATED_AT              TIMESTAMP,
    UPDATE_AT               TIMESTAMP


    CONSTRAINT PK_FEEDBACK_SRV_PAIEMENT PRIMARY KEY (ID),
);

ALTER TABLE AGREMENT ADD CONSTRAINT FK_SOCIETE FOREIGN KEY (ID_SOCIETE) REFERENCES
    SOCIETE (ID) ON DELETE CASCADE;


CREATE TABLE DET_CATEGORIE_TYPE_JOINTE
(
    ID                               NUMBER(8) NOT NULL,
    ID_CATEGORIE_TYPE_PIECE          NUMBER(8),
    ID_TYPE_PIECE                    NUMBER(8),

    CONSTRAINT PK_DET_CATEGORIE_TYPE_JOINTE PRIMARY KEY (ID),
);


ALTER TABLE DET_CATEGORIE_TYPE_JOINTE ADD CONSTRAINT FK_CATEGORY_TYPE_PIECE FOREIGN KEY (ID_CATEGORIE_TYPE_PIECE) REFERENCES
    CATEGORIE_TYPE_PIECE (ID) ON DELETE CASCADE;

ALTER TABLE DET_CATEGORIE_TYPE_JOINTE ADD CONSTRAINT FK_DET_CATEGORIE_TYPE_PIECE FOREIGN KEY (ID_TYPE_PIECE) REFERENCES
    TYPE_PIECE_JOINTE (ID) ON DELETE CASCADE;
