FROM node:lts-alpine as build-stage
WORKDIR /app
COPY package*.json ./
RUN npm ci
COPY ../../ .
RUN npm install
RUN npm run build --project iocav

FROM nginx:latest
RUN mkdir /app
COPY --from=build-stage /app/dist/iocav/browser/ /app
COPY ../../nginx.conf /etc/nginx/nginx.conf
USER root
