CREATE TABLE DECLARATION_DECHET
(
    ID_AUTORISATION       NUMBER(10)              NOT NULL,
    ID_TYPE_AUTORISATION  NUMBER(4)               NOT NULL,
    ID_FORMALITE          NUMBER(10)              NOT NULL,
    PRODUITS              VARCHAR2(254),
    QUANTITE              FLOAT,
    PROVENANCE            VARCHAR2(254),
    NATURE_PRODUIT        VARCHAR2(254),
    POIDS_NET             FLOAT,
    DESIGNATION           VARCHAR2(254),
    ORIGINE               VARCHAR2(254),
    ID_NAVIRE             NUMBER(10),
    DATE_EMBARQUEMENT     DATE,
    NOMBRE_CARTON         NUMBER(10),
    DATE_ARRIVEE          DATE,
    NOMBRE_TOTAL          NUMBER(10),
    DATE_PRODUCTION       DATE,
    CONTENEUR             VARCHAR2(254),
    TYPE_DECHETS          VARCHAR2(254),
    CONSTRAINT PK_ICCD_AUTORISATION PRIMARY KEY (ID_AUTORISATION)
);